export const METADATA_MIDDLEWARES = 'METADATA_MIDDLEWARES';
export const METADATA_MIDDLEWARES_VALIDATION = 'METADATA_MIDDLEWARES_VALIDATION';
export const METADATA_MIDDLEWARES_AUTH = 'METADATA_MIDDLEWARES_AUTH';
export const METADATA_MIDDLEWARES_AUTH_FN = 'METADATA_MIDDLEWARES_AUTH_FN';
export const METADATA_MIDDLEWARES_ROLE_FN = 'METADATA_MIDDLEWARES_ROLE_FN';
export const METADATA_PARAMS = 'METADATA_PARAMS';
export const METADATA_PATHS = 'METADATA_PATHS';
export const METADATA_ROUTES = 'METADATA_ROUTES';
export const METADATA_RULES = 'METADATA_RULES';
export const METADATA_MESSAGES = 'METADATA_MESSAGES';
export const METADATA_AUTHENTICATION = 'METADATA_AUTHENTICATION';

export const ACTION_TYPES: { [x: string]: string } = {
  ALL: 'all',
  DELETE: 'delete',
  GET: 'get',
  HEAD: 'head',
  OPTIONS: 'options',
  PATCH: 'patch',
  POST: 'post',
  PUT: 'put'
};
